version: '3.7'
services:
  postgres:
    image: postgres:9.5
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: password
  web:
    build:
      context: ${RAILS_APP}
      args:
        RUBY_VERSION: ${RUBY_VERSION}
        RAILS_VERSION: ${RAILS_VERSION}
      dockerfile: Dockerfile
      target: rails
    image: "correkthorse/rails:${CVE}"
    volumes:
      - "${RAILS_APP}:/app"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/
      BUNDLE_PATH: .bundle
    ports:
      - "3000:3000"
      - "3333:3333"
    depends_on:
      - postgres
volumes:
  postgres:
